
# login path for login user
# admin: email, password, 
User.destroy_all
admin = User.create!(name: 'Ivy', email: 'email@gmail.com', password: '1234', password_confirmation: '1234', isAdmin: true)
User.create!(name: 'test', email: 'test@email.com', password: 'password', password_confirmation: 'password')

Route.destroy_all
route = Route.create!(name: 'Lady Luck', location: 'Big Bear', difficulty: '5.9', pitches: '1, 100ft', description: 'Jam, stem and lieback your way up large flakes clipping bolts as you go. The crux is near the top and involves a somewhat wild move to get established on the upper face that leads to the anchors. 
Short and kinda scrappy but perhaps still worth doing as a warmup or whilst waiting for nearby routes to free up.', route_type: 'Sport', user_id: admin.id)
route2 = Route.create!(name: 'Mr. Bad Luck', location: 'Stone Crag', difficulty: '5.11c', pitches: '2, 190ft', description: "(1) Start up the first pitch of Firefly, climbing past that route's first three bolts. About 15 feet above the third bold, traverse left on casual terrain and up to a large ledge with chains. Walk left past the chains on the ledge for another 15 feet to a right-facing dihedral capped by a small roof, above which is a bolt. Go up the dihedral a ways to enjoyable face climbing past the bolt and then another to Brunch Ledge. 120' 5.9. 
(2) Jam the obvious overhanging hand crack until possible to move right and up clipping three bolts en route to the crux. Above, either step right to get some gear (and a rest) or swallow hard and punch it to the last bolt and one last set of difficult moves to chains. This pitch was bolted to avoid two sets of huge loose blocks; don't be tempted to go yonder lest you risk devastatingly bad luck. 70' 5.11. 
Trad rack, one each from small brass/steel (offsets useful) to a no.1 camalot; two no.2 camalots for the hand crack.", route_type: 'Sport', user_id: admin.id)
route3 = Route.create!(name: 'Bad Wolf', location: 'Mountains', difficulty: 'V4', pitches: '1, 30ft', description: "Start in the back of the cave on 2 crimps just left of the vertical limestone drip. Traverse left on good good holds and a ramp for your feet until the ramp drops away. Keep going to the lip of the cave, and top out straight up. The top out isn't hard, but it is heady.
Once you top out, hike up the hill side to the High Wire Right approach fixed lines to get back to the cave.", route_type: 'Boulder', user_id: admin.id) 
Route.create!(name: 'Another One', location: 'Somewhere', difficulty: '5.10a', pitches: '1, 120ft', description: "P1: This is the best pitch. Follow a straight in crack in a shallow LF dihedral for 130ft. The first 100ft are continuous, but rests can be found on dikes. Not a great first 5.9 - should be solid at the grade. Take care placing protection in the first 30 feet. P2: Continue up the crack system which turns right facing. Belay before a roof. P3: Short pitch. Climb the roof and descend to the left on a well marked trail. ", route_type: 'Sport', user_id: admin.id)
Route.create!(name: 'High Exposure', location: 'High Buttress',difficulty: '5.6', pitches: '2, 250ft', description: "The High E buttress is an obvious right-facing arete that is visible from the drive in from New Paltz. It is located about halfway along the base of the Trapps, right of the MF area and left of Bonnie's Roof. The High E access trail is about a 15 minute walk from the Uberfall.
P1 (5.4, 180'): Begin the climb in a chimney/stemming corner left of the arete. Climb up this corner, only until it is possible to traverse up and right across the face, then climb up the face to a fantastic, spacious triangular belay ledge (this is the GT ledge) right on the arete below a large roof. Belay from natural gear or sling the huge boulder on the ledge.
P2 (5.6, 100'): This is the money pitch, Climb up from the ledge (it's easiest to begin at the left side) and traverse right to the obvious place to turn the corner and make the move to pull the roof - the exposure is immediate and the rock is steep! Continue up the face past gear, jugs, and fixed pins, trending left back towards the arete, until you top out. Exhilarating!", route_type: 'Trad', user_id: admin.id) 
Route.create!(name: 'Snake Dike', location: 'Yosemite', difficulty: '5.7 R', pitches: '8, 2000ft', description: "Get to the SW shoulder of Half Dome by following the Muir Trail to the Mist Trail past Nevada Falls, then back on the Muir Trail. From the top of Nevada Falls, continue for 0.75 mile to an obvious climber's trail that heads off to the left, contouring around behind the back of Liberty Cap to Half Dome. You'll pass a swampy area (Lost Lake), and then wander up slabs to the south face of Half Dome, heading back left across ledges to the base of the route. The approach is six miles and takes 2.5 to 4 hours. 
P1: The route starts up a slab below a prominent upside-down L-shaped roof formation. A big tree is up in this roof area on the right. Climb up into the roof, then traverse out the left end and up onto a nice belay ledge. 5.7. 
P2: Continue up the left-facing corner system above and past a pair of bolts (optional belay), then wander right past another bolt to a bolted anchor. 5.7. 
P3: Climb up and left past a bolt and 5.7 friction to reach the dike itself. Skip another bolted belay, climbing up the dike past a bolt and easier climbing, and up to a bolted belay. 
P4, P5, P6: Follow the dike for three more long pitches, all about 5.4, all very run out, stopping at bolted anchors. The final anchor is at a point past a steep section on a small ledge. 
P7, P8: Lots of low angle climbing (easy 5th class) wander up the face with occasional gear placements. 
Once you feel comfortable unroping, do so, and continue scrambling up 1000' of calf-burning slabs to the summit. Descent is down the Half Dome Cables route. You can't miss it.  6 draws/slings, three or four small-medium sized cams.", route_type: 'Trad', user_id: admin.id)
Route.create!(name: 'White Rastafarian', location: 'Joshua Tree', difficulty: 'V2', pitches: '1, 20ft', description: "This problem is located on a large boulder at the Southeast end of Rock Hudson. Climb a juggy crack on an overhanging arete until it dies out 15 ft. up. Lean out left, onto the overhanging face, to a large flake. Finishes with an easy mantel 25 ft. off the deck. One of JTree's finest problems.", route_type: 'Boulder', user_id: admin.id) 
Route.create!(name: 'The Nose', location: 'Yosemite', difficulty: '5.9', pitches: '31, 3000ft', description: "Although this is a great climb the route is still very demanding, sustained and exposed and not to be taken lightly. Bring two sets of nuts with offsets, one or two sets of micro nuts with offsets and two or three sets of cams from .5 to 3.5. Also bring some micro cams and a 4.5 cam, leave the hammer and pins at home this route goes all clean.", route_type: 'Trad', user_id: admin.id)
Route.create!(name: 'Jedi Mind Tricks', location: 'Bishop', difficulty: 'V4 PG13', pitches: '1, 25ft', description: " The crux is right off the ground with very poor feet. Once you are high enough to use the flake with your feet it is smooth sailing to the very last move, which is the mental crux.", route_type: 'Boulder', user_id: admin.id) 
Route.create!(name: "Bear's Reach", location: 'Lake Tahoe', difficulty: '5.7', pitches: '3, 400ft', description: "P1: Start in a short right facing flake for about 20ft, Do a short unprotected traverse up and left to another lieback flake. Continue upwards into a left facing flake system, which will take some larger gear. The short runnout at the beginning of this pitch, though easy climbing, has resulted in a couple helicopter rescues, claimed a few ankles and caused a few good falls over the years. Climb slow and keep under control with an alert and competent belayer, or choose another route until you're 100% confident. P2: The reach pitch. Follow fun cracks and face holds to the large reach. Continue up on solid 5.6 overlaps to a good ledge. P3: Follow a right leaning crack system with a wide crack over a roof/bulge to the top, or traverse right up a low angle sloping ramp to the top.", route_type: 'Sport', user_id: admin.id)
Route.create!(name: 'Pistol Pete', location: 'Big Bear', difficulty: '5.10a/b', pitches: '1, 80ft', description: "Climb the slab passing two bolts (use a long draw or runner on the 2nd bolt) to a sloping ledge below the main face. Clip the third bolt, work up and right via an undercling flake and then continue up the featured face/arete to a small stance at the 7th bolt. Above here the climb changes character (again) and finishes up the exposed slabby arete via delicate, balancy moves.", route_type: 'Sport', user_id: admin.id) 
Route.create!(name: 'Holey Moley', location: 'New Jack City', difficulty: '5.10a', pitches: '1, 90ft', description: "Start just left of The Raven, below a series of huecos on the blunt arete. Climb the steep huecos past 3 bolts to a ledge, continue up to a short left facing corner and into the lower angle ramp/large hueco. Step up and left onto a small ledge and then back right to a horozontal dike with some large crystals. climb onto the dike(crux) and face climb up, slightly right at the bulge then back left to the anchor. Extending with longer draws the 4th and 6th(chicken bolts) will help with rope drag on this long route.", route_type: 'Sport', user_id: admin.id)
Route.create!(name: 'Powder Keg', location: 'Big Bear', difficulty: '5.10a', pitches: '1, 40ft', description: "Up a slippery slab (harder than it looks) to some good holds under the roof and then power out the somewhat reachy roof with a wild sequence to finish on easy slab to anchors - fun! ", route_type: 'Sport', user_id: admin.id) 
Route.create!(name: 'Delicious', location: 'Malibu Creek', difficulty: '5.10d', pitches: '1, 85ft', description: "One of the best in the park, this route has become very popular. It begins on the right end of the wall and begins on whitish/tan rock heading up & left up to a large bathtub sized hueco. From there you go up & out the right side, & power through a steep bulge where you'll find the crux(5.10+)getting to the 7th bolt. The upper 40 feet of this route are on amazing rock and it's only 5.9+. 10 bolts to sport anchors. Long runners/long draws recommended for bolt #'s 3, 5, 8 & 10.", route_type: 'Sport', user_id: admin.id)
Route.create!(name: 'Tangerine Dream', location: 'Riverside Quarry', difficulty: '5.10d', pitches: '1, 90ft', description: "Up the orange streak. A suberb mid-length route that features two distinct crux sections - the lower one with it's balancy, steep slab in the orange section and the upper one with strenuous liebacks and underclings as you fight the pump to the anchors on huge holds.", route_type: 'Sport', user_id: admin.id)
Route.create!(name: 'Mr. Magoo', location: 'Castle Rock', difficulty: 'V1-2', pitches: '1, 10ft', description: "Sit start on the two obvious hand holds. Throw high to a small shelf. Then head straight up to top out. Top out is the same as route 5, Up and Over.", route_type: 'Boulder', user_id: admin.id) 
Route.create!(name: "Charlotte's Web", location: 'The Brickyard', difficulty: 'V2', pitches: '1, 20ft', description: "Start with the left hand on a good side-pull crimp and the right on a mediocre crimp. After the first ten feet or so the grade drops to VB-.", route_type: 'Boulder', user_id: admin.id)
Route.create!(name: 'Jaws', location: 'Mt Woodson', difficulty: '5.11a/V1', pitches: '1, 15ft', description: "Jaws is the mean looking finger crack on the north face of JAWS. The climb widens from fingers to thin hands with insecure feet.", route_type: 'Trad, Boulder', user_id: admin.id) 
Route.create!(name: 'Sundance', location: 'Tahquitz', difficulty: '5.10b', pitches: '3, 300ft', description: "Scramble up to a ledge with a pine tree directly below Log Ledge, a sloping shelf with a dead log, then walk left to a left-facing flake system which is the start of the route. 
P1) Lieback up the widening crack (5.8) to reach a small ledge where another left-facing corner (5.9) leads to the left side of Log Ledge and a 2 bolt anchor. 
P2) Make some thin moves off the belay (crux) and then wander up the incredible face above past five bolts. After the last bolt traverse right (5.9) to gain the arete of a left-facing flake system which is climbed 20' or so without pro (5.6) to a stance atop the flake with a 2 bolt belay. 
P3) Climb face past two bolts into a thin crack with tricky gear placements or head left after the second bolt, via the popular Sundike variation, past two more bolts. Mostly bolts with supplemental gear to 4 inches.", route_type: 'Trad', user_id: admin.id)

